### Post articles
POST http://localhost:3000/api/articles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViMzViNmNkZjhlZjBiMjUzYWI1N2Q5MyIsInVzZXJuYW1lIjoidGVzdCIsImV4cCI6MTUzNTQ1Nzg2MCwiaWF0IjoxNTMwMjczODYwfQ.ZVoVL4xvTCHq92MGybdxfKOQ0iPaimJwkvX97NTosxA

{
  "article": {
    "title": "The Concept of CSS",
    "description": "A comprehensive guide to using CSS to build servers",
    "body": "A comprehensive guide to using CSS to build servers",
    "tagList": ["CSS"],
    "favoritesCount": 1
  }
}

### Retrieve articles
GET http://localhost:3000/api/articles

### Retrieve feed
GET http://localhost:3000/api/articles/feed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViMzRjN2QyYmFjZWVmYzk0ZDViMDU0MiIsInVzZXJuYW1lIjoiZm9vYmFyIiwiZXhwIjoxNTM2MDM2Mzg1LCJpYXQiOjE1MzA4NTIzODV9.VMsRxUQ6Gr2zHjGqIzxvtwBPqLLThX1BPv9QgP2Vmt0

### Retrieve article
GET http://localhost:3000/api/articles/the-concept-of-rails-3pxp24

### Delete article
DELETE http://localhost:3000/api/articles/the-concept-of-rails-moxcoz
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViMzViNmNkZjhlZjBiMjUzYWI1N2Q5MyIsInVzZXJuYW1lIjoidGVzdCIsImV4cCI6MTUzNTQ1Nzg2MCwiaWF0IjoxNTMwMjczODYwfQ.ZVoVL4xvTCHq92MGybdxfKOQ0iPaimJwkvX97NTosxA

### Favorite article
POST http://localhost:3000/api/articles/the-concept-of-rails-4m1yxf/favorite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViMzViNmNkZjhlZjBiMjUzYWI1N2Q5MyIsInVzZXJuYW1lIjoidGVzdCIsImV4cCI6MTUzNTQ1Nzg2MCwiaWF0IjoxNTMwMjczODYwfQ.ZVoVL4xvTCHq92MGybdxfKOQ0iPaimJwkvX97NTosxA
###
POST http://localhost:3000/api/articles/the-concept-of-rails-4m1yxf/favorite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViMzRjN2QyYmFjZWVmYzk0ZDViMDU0MiIsInVzZXJuYW1lIjoiZm9vYmFyIiwiZXhwIjoxNTM1NTE4NzMxLCJpYXQiOjE1MzAzMzQ3MzF9.IHdlrmWtlSGFap4u1k8w--9-Vp63F3jLP3r8vqx40Ng

### Unfavorite article
DELETE http://localhost:3000/api/articles/the-concept-of-rails-4m1yxf/favorite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViMzRjN2QyYmFjZWVmYzk0ZDViMDU0MiIsInVzZXJuYW1lIjoiZm9vYmFyIiwiZXhwIjoxNTM1NTE4NzMxLCJpYXQiOjE1MzAzMzQ3MzF9.IHdlrmWtlSGFap4u1k8w--9-Vp63F3jLP3r8vqx40Ng