### Follow user
POST http://localhost:3000/api/profiles/test2/follow
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViMzRjN2QyYmFjZWVmYzk0ZDViMDU0MiIsInVzZXJuYW1lIjoiZm9vYmFyIiwiZXhwIjoxNTM1NTQwNTI0LCJpYXQiOjE1MzAzNTY1MjR9.rrhag756639wSPCKDPqB2h5-PZh4sekXSLaYyuHD6nQ

### Unfollow user
DELETE http://localhost:3000/api/profiles/test2/follow
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViMzRjN2QyYmFjZWVmYzk0ZDViMDU0MiIsInVzZXJuYW1lIjoiZm9vYmFyIiwiZXhwIjoxNTM1NTQwNTI0LCJpYXQiOjE1MzAzNTY1MjR9.rrhag756639wSPCKDPqB2h5-PZh4sekXSLaYyuHD6nQ